[package]
authors = ["Sean Bowe <ewillbefull@gmail.com>"]
description = "zk-SNARK library"
documentation = "https://github.com/ebfull/bellman"
homepage = "https://github.com/ebfull/bellman"
license = "MIT/Apache-2.0"
name = "bellman"
repository = "https://github.com/ebfull/bellman"
version = "0.1.0"

[dependencies]
rand = "0.4"
bit-vec = "0.4.4"
ff = "0.4"
futures = "0.1"
futures-cpupool = "0.1"
group = "0.1"
num_cpus = "1"
crossbeam = "0.3"
pairing = { path = "../pairing", optional = true }
byteorder = "1"

[features]
groth16 = ["pairing"]
default = ["groth16"]

[[test]]
name = "mimc"
path = "tests/mimc.rs"
required-features = ["groth16"]
